resolver: lts-11.3

packages:
- .

extra-deps:
- hsqml-0.3.5.1

nix:
  enable: true
  pure: true
  packages:
  - pcre
  - libxml2
  - zlib
  - lzma
  - pkgconfig
  - qt5.qtbase
  - qt5.qtx11extras
  - qt5.qtdeclarative
  - qt5.qtquickcontrols2
  - qt5.qtwebengine
